import { test, expect, type Page } from '@playwright/test';
import { createClient } from '@supabase/supabase-js';
import { randomUUID } from 'node:crypto';
if (!['localhost', '127.0.0.1'].includes(new URL(process.env.NEXT_PUBLIC_SUPABASE_URL!).hostname)) throw new Error('Category browser tests require a local development database');
const admin = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.SUPABASE_SERVICE_ROLE_KEY!, { auth: { persistSession: false } });
const origin = { Origin: 'http://localhost:3000' };
async function resource(page: Page, name: string, data: Record<string, unknown>, id?: string): Promise<string> {
  const response = await page.request.post(`/api/data/${name}`, { headers: origin, data: { data, id } });
  expect(response.ok(), await response.text()).toBe(true);
  return (await response.json()).id;
}
test('hierarchy groups monthly cash and installments once, filters roots and children, reparents safely and preserves archived history on mobile', async ({ page }) => {
  test.setTimeout(120000);
  const email = `categories-${randomUUID()}@example.test`, password = randomUUID() + 'Aa1!';
  const user = await admin.auth.admin.createUser({ email, password, email_confirm: true });
  expect(user.error).toBeNull();
  try {
    await page.goto('/');
    await page.getByLabel('E-mail').fill(email);
    await page.getByLabel('Senha', { exact: true }).fill(password);
    await page.getByRole('button', { name: 'Entrar na minha conta' }).click();
    await expect(page.getByText('Saldo disponível', { exact: true })).toBeVisible();
    const account = await resource(page, 'financial_accounts', { name: 'Banco categorias', kind: 'bank', initial_balance: '1000' });
    const transport = await resource(page, 'categories', { name: 'Transportes', spending_kind: 'essential' });
    const food = await resource(page, 'categories', { name: 'Alimentação' });
    const uber = await resource(page, 'categories', { name: 'Uber', parent_id: transport });
    const bus = await resource(page, 'categories', { name: 'Ônibus', parent_id: transport });
    const card = await resource(page, 'credit_cards', { name: 'Cartão categorias', account_id: account, credit_limit: '5000', closing_day: 5, due_day: 10, last_four: '1234' });
    const date = `${new Intl.DateTimeFormat('en-CA', { timeZone: 'America/Sao_Paulo' }).format(new Date()).slice(0, 7)}-01`;
    const op = async (action: string, payload: Record<string, unknown>) => {
      const response = await page.request.post('/api/operations', { headers: origin, data: { action, payload, request_id: randomUUID() } });
      expect(response.ok(), await response.text()).toBe(true);
      return await response.json();
    };
    await op('transaction', { account_id: account, category_id: transport, description: 'Transporte direto', amount: '50', date, type: 'expense', status: 'confirmed' });
    await op('transaction', { account_id: account, category_id: uber, description: 'Viagem Uber', amount: '250', date, type: 'expense', status: 'confirmed' });
    await op('transaction', { account_id: account, category_id: bus, description: 'Passe ônibus', amount: '100', date, type: 'expense', status: 'confirmed' });
    await op('transaction', { account_id: account, category_id: food, description: 'Refeição', amount: '30', date, type: 'expense', status: 'confirmed' });
    await op('purchase', { card_id: card, category_id: uber, description: 'Passe parcelado', amount: '300', installments: 3, date });
    await page.reload();
    await expect(page.getByRole('article', { name: 'Gastos do mês', exact: true })).toContainText('R$ 530,00');
    const distribution = page.locator('section').filter({ has: page.getByRole('heading', { name: 'Onde você mais gasta', exact: true }) });
    await expect(distribution).toContainText('R$ 500,00');
    await distribution.getByRole('button', { name: 'Detalhar Transportes', exact: true }).click();
    await expect(distribution).toContainText('Direto em Transportes');
    await expect(distribution).toContainText('R$ 350,00');
    await expect(distribution).toContainText('R$ 100,00');
    await page.goto('/transacoes');
    await page.getByLabel('Filtrar transações por categoria').selectOption(transport);
    await expect(page.locator('.table-wrap tbody tr')).toHaveCount(3);
    await expect(page.locator('.table-wrap')).toContainText('Transportes / Uber');
    await page.getByLabel('Filtrar transações por categoria').selectOption(uber);
    await expect(page.locator('.table-wrap tbody tr')).toHaveCount(1);
    await page.goto('/categorias');
    const categoryPanel = page.locator('.category-management > .panel').filter({ has: page.getByRole('heading', { name: 'Transportes', exact: true }) });
    await expect(categoryPanel).toContainText('R$ 500,00');
    await expect(categoryPanel.locator('.category-child-row')).toHaveCount(2);
    await categoryPanel.getByRole('button', { name: 'Editar subcategoria Uber', exact: true }).click();
    const edit = page.getByRole('dialog', { name: 'Editar subcategoria', exact: true });
    await edit.getByLabel('Categoria principal', { exact: true }).selectOption(food);
    await edit.getByRole('button', { name: 'Salvar', exact: true }).click();
    await expect(edit).not.toBeVisible();
    await expect(categoryPanel).toContainText('R$ 150,00');
    const updatedUber = await admin.from('transactions').select('category_id,amount::text').eq('user_id', user.data.user!.id).eq('description', 'Viagem Uber').single();
    expect(updatedUber.data).toMatchObject({ category_id: uber, amount: '-250.00' });
    await page.goto('/transacoes');
    await page.getByRole('button', { name: 'Novo lançamento', exact: true }).click();
    const form = page.getByRole('dialog', { name: 'Novo lançamento', exact: true });
    await expect(form.getByLabel('Categoria', { exact: true }).locator('option')).toHaveCount(3);
    await form.getByLabel('Categoria', { exact: true }).selectOption(food);
    await expect(form.getByLabel('Subcategoria de Alimentação')).toBeVisible();
    await form.getByLabel('Subcategoria de Alimentação').selectOption(uber);
    await expect(form).toContainText('Alimentação → Uber');
    await form.getByRole('button', { name: 'Fechar', exact: true }).click();
    await page.goto('/relatorios');
    await page.getByLabel('Filtrar relatório por categoria').selectOption(food);
    await page.getByLabel('Subcategoria de Alimentação').selectOption(uber);
    const report = page.locator('section').filter({ has: page.getByRole('heading', { name: 'Categorias e subcategorias no período', exact: true }) });
    await expect(report).toContainText('R$ 350,00');
    await page.getByLabel('Filtrar relatório por cartão').selectOption(card);
    await expect(report).toContainText('R$ 100,00');
    await page.screenshot({ path: 'test-results/categories-desktop.png', fullPage: true });
    await page.setViewportSize({ width: 390, height: 844 });
    const overflowing = await page.evaluate(() => [...document.querySelectorAll('main *')].filter(element => element.getBoundingClientRect().right > innerWidth + 1).map(element => ({ tag: element.tagName, className: element.className, right: element.getBoundingClientRect().right })).slice(0, 18));
    await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), { message: JSON.stringify(overflowing) }).toBe(true);
    await page.screenshot({ path: 'test-results/categories-mobile.png', fullPage: true });
    await page.goto('/categorias');
    await categoryPanel.getByRole('button', { name: 'Excluir', exact: true }).first().click();
    const remove = page.getByRole('dialog', { name: 'Excluir categoria?', exact: true });
    await expect(remove).toContainText('totais históricos serão preservados');
    await remove.getByRole('button', { name: 'Excluir', exact: true }).click();
    await expect(remove).not.toBeVisible();
    await expect(categoryPanel).toHaveCount(0);
    const preserved = await admin.from('transactions').select('category_id,amount::text').eq('user_id', user.data.user!.id).eq('description', 'Passe ônibus').single();
    expect(preserved.data).toMatchObject({ category_id: bus, amount: '-100.00' });
    const archived = await admin.from('categories').select('id,archived').in('id', [transport, bus]);
    expect(archived.data).toHaveLength(2);
    expect(archived.data?.every(category => category.archived)).toBe(true);
  } finally { await admin.auth.admin.deleteUser(user.data.user!.id); }
});
