import { test, expect, type Page } from '@playwright/test';
import { createClient } from '@supabase/supabase-js';
import { randomUUID } from 'node:crypto';
const url=process.env.NEXT_PUBLIC_SUPABASE_URL!;
if(!['localhost','127.0.0.1'].includes(new URL(url).hostname))throw Error('Manual investment browser checks are local only');
const admin=createClient(url,process.env.SUPABASE_SERVICE_ROLE_KEY!,{auth:{persistSession:false}});
const today=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo'}).format(new Date());
const month=(offset:number)=>{const d=new Date(today+'T12:00:00Z');d.setUTCDate(1);d.setUTCMonth(d.getUTCMonth()+offset);return d.toISOString().slice(0,7);};
const first=month(-2),second=month(-1);
async function login(page:Page){const email=`manual-ui-${randomUUID()}@example.test`,password=randomUUID()+'Aa1!';const user=await admin.auth.admin.createUser({email,password,email_confirm:true});expect(user.error).toBeNull();try{await page.goto('/');await page.getByLabel('E-mail').fill(email);await page.getByLabel('Senha',{exact:true}).fill(password);await page.getByRole('button',{name:'Entrar na minha conta'}).click();await expect(page.getByText('Saldo disponível',{exact:true})).toBeVisible();return user.data.user!.id;}catch(error){await admin.auth.admin.deleteUser(user.data.user!.id);throw error;}}
async function save(page:Page){await page.getByRole('dialog').getByRole('button',{name:'Salvar',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);}
test('manual fund purchases and monthly prices use exact capital, editable history and never move cash or request quotes',async({page})=>{
 test.setTimeout(90000);const id=await login(page);let quoteRequests=0;page.on('request',r=>{if(['/api/quotes','/api/assets','/api/sync'].includes(new URL(r.url()).pathname))quoteRequests++;});
 try{
  await page.goto('/investimentos');await expect(page.getByRole('button',{name:'Registrar operação'})).toHaveCount(0);await expect(page.getByRole('button',{name:'Novo ativo'})).toHaveCount(0);await expect(page.getByRole('button',{name:'Este mês',exact:true})).toHaveCount(0);
  await page.getByRole('button',{name:'Novo investimento',exact:true}).click();
  const dialog=page.getByRole('dialog');await dialog.getByLabel('Nome do investimento').fill('Fundo XPTO');await dialog.getByLabel('Tipo',{exact:true}).selectOption('fund');await dialog.getByLabel('Quantidade adquirida').fill('10');await dialog.getByLabel('Valor total investido (R$)').fill('1000');await dialog.getByLabel('Data da compra').fill(first+'-01');await save(page);
  const fund=page.getByRole('article',{name:'Investimento Fundo XPTO',exact:true});await expect(fund).toContainText('Aguardando atualização');
  await fund.getByRole('button',{name:'Adicionar compra',exact:true}).click();await dialog.getByLabel('Quantidade adquirida').fill('5');await dialog.getByLabel('Valor total investido (R$)').fill('600');await dialog.getByLabel('Data da compra').fill(first+'-10');await save(page);
  await expect(fund).toContainText('R$ 106,67');await expect(page.getByRole('article',{name:'Total investido',exact:true})).toContainText('R$ 1.600,00');
  await fund.getByRole('button',{name:'Atualizar valor',exact:true}).click();await dialog.getByLabel('Valor atual por unidade ou cota (R$)').fill('130');await dialog.getByLabel('Data da atualização').fill(first+'-20');await save(page);
  await expect(page.getByRole('article',{name:'Patrimônio atual',exact:true})).toContainText('R$ 1.950,00');await expect(page.getByRole('article',{name:'Lucro / prejuízo',exact:true})).toContainText('R$ 350,00');await expect(page.getByRole('article',{name:'Rentabilidade acumulada',exact:true})).toContainText('+21,88%');
  await fund.getByRole('button',{name:'Adicionar compra',exact:true}).click();await dialog.getByLabel('Quantidade adquirida').fill('5');await dialog.getByLabel('Valor total investido (R$)').fill('650');await dialog.getByLabel('Data da compra').fill(second+'-01');await save(page);
  await fund.getByRole('button',{name:'Atualizar valor',exact:true}).click();await dialog.getByLabel('Valor atual por unidade ou cota (R$)').fill('130');await dialog.getByLabel('Data da atualização').fill(second+'-20');await save(page);
  await expect(fund).toContainText('Variação por unidade desde a atualização anterior: 0,00%');await expect(page.getByRole('article',{name:'Lucro / prejuízo',exact:true})).toContainText('R$ 350,00');
  const history=page.getByRole('region',{name:'Histórico mensal dos investimentos'});await expect(history).toContainText('Aplicado: R$ 1.600,00');await expect(history).toContainText('Aplicado: R$ 2.250,00');
  await fund.getByText('Histórico de compras · 3',{exact:true}).click();await fund.getByRole('button',{name:`Editar compra de Fundo XPTO em 10/${first.slice(5)}/${first.slice(0,4)}`}).click();await dialog.getByLabel('Valor total investido (R$)').fill('550');await save(page);await expect(page.getByRole('article',{name:'Total investido',exact:true})).toContainText('R$ 2.200,00');
  await fund.getByRole('button',{name:`Excluir compra de Fundo XPTO em 01/${second.slice(5)}/${second.slice(0,4)}`}).click();await dialog.getByRole('button',{name:'Excluir',exact:true}).click();await expect(dialog).toHaveCount(0);await expect(page.getByRole('article',{name:'Total investido',exact:true})).toContainText('R$ 1.550,00');
  await fund.getByText('Atualizações mensais · 2',{exact:true}).click();await fund.getByRole('button',{name:`Corrigir atualização de Fundo XPTO em ${second}`}).click();await dialog.getByLabel('Valor atual por unidade ou cota (R$)').fill('90');await save(page);await expect(page.getByRole('article',{name:'Lucro / prejuízo',exact:true})).toContainText('-R$ 200,00');
  const snapshot=await(await page.request.get('/api/snapshot')).json();expect(snapshot.manual_investment_purchases).toHaveLength(3);expect(snapshot.manual_investment_purchases.filter((r:{status:string})=>r.status==='confirmed')).toHaveLength(2);expect(snapshot.manual_investment_updates).toHaveLength(2);expect(snapshot.transactions).toHaveLength(0);expect(snapshot.financial_accounts).toHaveLength(0);
  expect(quoteRequests).toBe(0);
  await page.setViewportSize({width:820,height:1180});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:test.info().outputPath('manual-investments-tablet.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});await expect(fund.getByRole('button',{name:'Atualizar valor'})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.screenshot({path:test.info().outputPath('manual-investments-mobile.png'),fullPage:true});
 }finally{expect((await admin.auth.admin.deleteUser(id)).error).toBeNull();}
});
test('crypto fractional purchases share one asset, reject duplicate names and preserve waiting state',async({page})=>{
 const id=await login(page);try{
  await page.goto('/investimentos');await page.getByRole('button',{name:'Novo investimento'}).click();const dialog=page.getByRole('dialog');await dialog.getByLabel('Nome do investimento').fill('Bitcoin');await dialog.getByLabel('Tipo',{exact:true}).selectOption('crypto');await dialog.getByLabel('Quantidade adquirida').fill('0.002');await dialog.getByLabel('Valor total investido (R$)').fill('1000');await dialog.getByLabel('Data da compra').fill(today);await save(page);
  const bitcoin=page.getByRole('article',{name:'Investimento Bitcoin',exact:true});await bitcoin.getByRole('button',{name:'Adicionar compra'}).click();await dialog.getByLabel('Quantidade adquirida').fill('0.003');await dialog.getByLabel('Valor total investido (R$)').fill('1200');await dialog.getByLabel('Data da compra').fill(today);await save(page);
  await bitcoin.getByRole('button',{name:'Adicionar compra'}).click();await dialog.getByLabel('Quantidade adquirida').fill('0.001');await dialog.getByLabel('Valor total investido (R$)').fill('500');await dialog.getByLabel('Data da compra').fill(today);await save(page);await expect(bitcoin).toContainText('0,006');await expect(bitcoin).toContainText('R$ 450.000,00');await expect(page.getByRole('region',{name:'Criptomoedas',exact:true})).toContainText('Bitcoin');await expect(page.getByRole('article',{name:'Rentabilidade acumulada',exact:true})).toContainText('—');
  await page.getByRole('button',{name:'Novo investimento'}).click();await dialog.getByLabel('Nome do investimento').fill(' bitcoin ');await dialog.getByLabel('Tipo',{exact:true}).selectOption('crypto');await dialog.getByLabel('Quantidade adquirida').fill('1');await dialog.getByLabel('Valor total investido (R$)').fill('10');await dialog.getByLabel('Data da compra').fill(today);await dialog.getByRole('button',{name:'Salvar'}).click();await expect(dialog.getByRole('alert')).toContainText('Já existe um investimento');await dialog.getByRole('button',{name:'Fechar',exact:true}).click();
  const snapshot=await(await page.request.get('/api/snapshot')).json();expect(snapshot.investment_assets).toHaveLength(1);expect(snapshot.manual_investment_purchases).toHaveLength(3);
  await bitcoin.getByRole('button',{name:'Atualizar valor'}).click();await dialog.getByLabel('Valor atual por unidade ou cota (R$)').fill('500000');await dialog.getByLabel('Data da atualização').fill(today);await save(page);await expect(page.getByRole('article',{name:'Patrimônio atual',exact:true})).toContainText('R$ 3.000,00');
  await page.reload();await expect(page.getByRole('article',{name:'Lucro / prejuízo',exact:true})).toContainText('R$ 300,00');await page.screenshot({path:test.info().outputPath('manual-investments-desktop.png'),fullPage:true});
 }finally{expect((await admin.auth.admin.deleteUser(id)).error).toBeNull();}
});
