create role anon nologin;
create role authenticated nologin;
create role service_role nologin bypassrls;
create role authenticator login password :'db_password' noinherit;
grant anon,authenticated,service_role to authenticator;
create schema if not exists auth;
create schema if not exists extensions;
create function auth.uid() returns uuid language sql stable as $$select coalesce(nullif(current_setting('request.jwt.claim.sub',true),''),nullif(current_setting('request.jwt.claims',true),'')::jsonb->>'sub')::uuid$$;
grant usage on schema public,auth to anon,authenticated,service_role;
grant execute on function auth.uid() to anon,authenticated,service_role;
alter default privileges in schema public grant all on tables to service_role;
alter default privileges in schema public grant all on sequences to service_role;
alter default privileges in schema public grant all on functions to service_role;
