'use client';
import { useMemo, useState } from 'react';
import Link from 'next/link';
import { ArrowRight, CalendarClock, CircleAlert, Goal, PiggyBank, ShieldCheck, Wallet } from 'lucide-react';
import { D } from '@/financial/engine';
import { type Snapshot } from '@/lib/summary';
import { financialPlan } from '@/lib/financial-plan';
const brl = (value: string) => new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(Number(value));
const date = (value: string) => value.split('-').reverse().join('/');
export function FinancialPlanning({ snapshot, today, variant = 'full' }: { snapshot: Snapshot; today: string; variant?: 'full' | 'compact' }) {
  const plan = useMemo(() => financialPlan(snapshot, today), [snapshot, today]);
  const [horizon, setHorizon] = useState<30 | 60 | 90>(30);
  const forecast = plan.forecast.find(f => f.days === horizon)!;
  const { spendable, essentials } = plan;
  const shortage = D(spendable.deficit).gt(0);
  return <section className={`financial-planning ${variant}`} aria-label="Plano financeiro pessoal">
    <div className="planning-section-head"><div><span className="dashboard-overline">SEU DINHEIRO · PRÓXIMOS PASSOS</span><h2>Planeje com tranquilidade.</h2><p>Veja o que seus registros permitem fazer hoje e o que vem pela frente.</p></div>{variant === 'compact' && <Link href="/planejamento">Abrir planejamento <ArrowRight size={16} /></Link>}</div>
    <div className="planning-decision-grid">
      <article className={`planning-spendable ${shortage ? 'shortage' : ''}`} aria-label="Disponível para gastar até o fim do mês"><div><Wallet size={18} /><span>Quanto posso gastar até o fim do mês?</span></div><strong>{brl(spendable.available)}</strong><p>{shortage ? `Os compromissos superam o caixa de hoje em ${brl(spendable.deficit)}. Confira se as entradas previstas chegarão antes dos vencimentos.` : `${brl(spendable.perDay)} por dia até ${date(spendable.monthEnd)}, pelos registros atuais.`}</p><dl><div><dt>Entradas ainda previstas</dt><dd>{brl(spendable.income)}</dd></div><div><dt>Saídas e faturas previstas</dt><dd>{brl(spendable.expenses)}</dd></div><div><dt>Saldo projetado no fim do mês</dt><dd>{brl(spendable.balance)}</dd></div></dl><small>Disponível planejado: caixa de hoje menos compromissos até o fim do mês, sem antecipar receitas. Compras novas e despesas ainda não lançadas reduzem esse valor. Rendimentos estimados e limites de cartão ficam de fora.</small></article>
      <article className="planning-reserve" aria-label="Reserva de emergência em meses"><div className="planning-card-title"><ShieldCheck size={18} /><h3>Seu colchão de segurança</h3></div><strong>{essentials.months === null ? 'Vamos medir sua reserva' : `${Number(essentials.months).toLocaleString('pt-BR', { maximumFractionDigits: 1 })} meses`}</strong><p>{essentials.months === null ? 'Marque despesas essenciais e identifique a caixinha destinada à emergência.' : 'de despesas essenciais médias cobertas pela reserva identificada.'}</p><dl><div><dt>Essenciais por mês</dt><dd>{essentials.monthly === null ? 'Classifique as categorias' : brl(essentials.monthly)}</dd></div><div><dt>Reserva registrada</dt><dd>{essentials.reserve === null ? 'Identifique sua caixinha' : brl(essentials.reserve)}</dd></div><div><dt>Objetivo · {essentials.targetMonths} meses</dt><dd>{essentials.target === null ? 'Histórico em formação' : brl(essentials.target)}</dd></div>{essentials.gap !== null && <div><dt>Falta para o objetivo</dt><dd>{brl(essentials.gap)}</dd></div>}</dl><p className="planning-sample">Base: {essentials.sampleMonths} de 3 meses anteriores com registros.{essentials.missingCategories > 0 ? ` Há ${essentials.missingCategories} gastos sem classificação; a cobertura pode estar superestimada.` : ''}</p><div className="planning-links"><Link href="/categorias">Classificar essenciais</Link><Link href="/caixinhas">Identificar reserva</Link><Link href="/configuracoes">Ajustar objetivo</Link></div><small>Use uma reserva com liquidez adequada. Rendimento projetado e outros investimentos não são tratados como caixa de emergência.</small></article>
    </div>
    <section className="panel planning-forecast" aria-label="Previsão de caixa para 30, 60 e 90 dias"><div className="panel-head"><div><h3>O caminho do seu caixa</h3><p>Saldo previsto com contas, faturas, recorrências e recebimentos cadastrados.</p></div><CalendarClock size={20} /></div>
      <div className="forecast-horizons">{plan.forecast.map(item => <button key={item.days} type="button" className={horizon === item.days ? 'selected' : ''} aria-pressed={horizon === item.days} onClick={() => setHorizon(item.days)}><span>{item.days} dias · até {date(item.endDate)}</span><strong className={D(item.balance).lt(0) ? 'negative' : ''}>{brl(item.balance)}</strong><small>{item.items.length} movimentos previstos</small></button>)}</div>
      <div className="forecast-totals"><div><span>Caixa disponível hoje</span><strong>{brl(forecast.opening)}</strong></div><div><span>Entradas previstas</span><strong className="positive">+ {brl(forecast.income)}</strong></div><div><span>Saídas previstas</span><strong>− {brl(forecast.expenses)}</strong></div><div><span>Menor saldo previsto</span><strong className={D(forecast.minimumBalance).lt(0) ? 'negative' : ''}>{brl(forecast.minimumBalance)}</strong><small>{date(forecast.minimumDate)}</small></div></div>
      {D(forecast.minimumBalance).lt(0) && <p className="planning-alert"><CircleAlert size={16} />Seu caixa pode ficar negativo em {date(forecast.minimumDate)}. Revise os vencimentos ou planeje uma entrada antes dessa data.</p>}
      <details className="forecast-details" open={variant === 'full'}><summary>Ver os compromissos dos próximos {horizon} dias</summary>{forecast.items.length ? <div className="forecast-events">{forecast.items.map(item => <article key={item.id}><span className={`forecast-event-icon ${D(item.amount).lt(0) ? 'out' : ''}`}>{item.kind === 'invoice' ? <Wallet size={16} /> : <CalendarClock size={16} />}</span><div><strong>{item.description}</strong><small>{date(item.date)} · {item.source}</small></div><div><b className={D(item.amount).lt(0) ? 'negative' : 'positive'}>{brl(item.amount)}</b><small>Previsto</small></div></article>)}</div> : <p className="planning-empty">Não há movimentos futuros cadastrados nessa janela. Adicione recorrências e obrigações para construir uma previsão útil.</p>}</details>
      <p className="planning-note">Valores previstos não foram recebidos nem pagos. A fatura representa o desembolso do cartão; suas parcelas não são somadas novamente como despesa de caixa.</p>
    </section>
    {plan.alerts.length > 0 && <section className="planning-alerts" aria-label="Alertas financeiros">{plan.alerts.map(alert => <article className={alert.severity} key={alert.id}><CircleAlert size={18} /><div><strong>{alert.title}</strong><p>{alert.description}</p>{alert.amount && <p><b>{alert.id === 'cash-shortfall' ? 'Saldo previsto' : 'Valor'}: {brl(alert.amount)}</b>{alert.date && ` · ${date(alert.date)}`}</p>}</div><Link href={alert.href} aria-label={`Revisar: ${alert.title}`}><ArrowRight size={18} /></Link></article>)}</section>}
    <section className="panel planning-goals" aria-label="Aporte necessário para suas metas"><div className="panel-head"><div><h3>Transforme seus planos em aportes</h3><p>Quanto guardar por mês para atingir suas metas, sem presumir rendimento futuro.</p></div><Goal size={21} /></div>{plan.goals.length ? <div className="planning-goal-grid">{(variant === 'compact' ? plan.goals.slice(0, 4) : plan.goals).map(goal => <article key={goal.id}><div><PiggyBank size={18} /><strong>{goal.name}</strong></div><dl><div><dt>Valor registrado</dt><dd>{brl(goal.current)}</dd></div><div><dt>Objetivo</dt><dd>{brl(goal.target)}</dd></div><div><dt>Falta guardar</dt><dd>{brl(goal.remaining)}</dd></div></dl><div className={`planning-goal-contribution financial-surface ${D(goal.remaining).eq(0) ? "tone-paid" : goal.deadlineState === "overdue" ? "tone-danger" : "tone-wealth"}`}><span>{D(goal.remaining).eq(0) ? 'Objetivo alcançado' : goal.deadlineState === 'overdue' ? 'Revise o prazo da meta' : goal.monthlyContribution !== null ? 'Aporte mensal necessário' : 'Defina uma data para calcular'}</span><strong>{D(goal.remaining).eq(0) ? <CheckMark /> : goal.monthlyContribution !== null ? brl(goal.monthlyContribution) : '—'}</strong><small>{goal.deadline ? `${goal.deadlineState === 'overdue' ? 'Prazo vencido' : 'Prazo'}: ${date(goal.deadline)}` : 'Edite a meta e escolha uma data viável.'}</small></div></article>)}</div> : <p className="planning-empty">Cadastre uma caixinha ou meta financeira com valor e prazo para conhecer seu aporte mensal.</p>}<Link className="planning-end-link" href={variant === 'compact' ? '/planejamento' : '/caixinhas'}>{variant === 'compact' ? 'Organizar todas as minhas metas' : 'Cuidar das minhas caixinhas'} <ArrowRight size={15} /></Link></section>
  </section>;
}
function CheckMark() { return <span className="positive">✓</span>; }
