import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { createClient } from '@supabase/supabase-js';
import { manualSavingsPosition, manualSavingsHistory } from '../src/lib/manual-savings';
import type { Snapshot } from '../src/lib/summary';
const url=process.env.NEXT_PUBLIC_SUPABASE_URL!;
if(!['localhost','127.0.0.1'].includes(new URL(url).hostname))throw Error('Manual savings tests require local isolated data');
const admin=createClient(url,process.env.SUPABASE_SERVICE_ROLE_KEY!,{auth:{persistSession:false}});
const today=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo'}).format(new Date());
const old=new Date(`${today.slice(0,7)}-01T12:00:00Z`);old.setUTCMonth(old.getUTCMonth()-1);const earlier=old.toISOString().slice(0,10);
const users:string[]=[];let checks=0;const pass=(m:string)=>{checks++;console.log(`PASS ${m}`);};
async function client(){const email=`savings-${randomUUID()}@example.test`,password=randomUUID()+'Aa1!';const r=await admin.auth.admin.createUser({email,password,email_confirm:true});assert.equal(r.error,null);users.push(r.data.user!.id);const db=createClient(url,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,{auth:{persistSession:false}});assert.equal((await db.auth.signInWithPassword({email,password})).error,null);return db;}
try {
 const db=await client(),other=await client();const op=(action:string,payload:Record<string,unknown>,request_id=randomUUID())=>db.rpc('manual_savings_operation',{action,payload,request_id});
 const account=await db.from('financial_accounts').insert({name:'Bank',kind:'bank',initial_balance:'5000'}).select('id').single();assert.equal(account.error,null);const account_id=account.data!.id;
 const nonce=randomUUID(),input={name:'Manual reserve',target:'2000',initial_balance:'1000',account_id:'',date:earlier};
 const created=await op('create',input,nonce);assert.equal(created.error,null);const goal_id=created.data.goal_id;
 assert.deepEqual((await op('create',input,nonce)).data,created.data);assert.ok((await op('create',{...input,initial_balance:'999'},nonce)).error);pass('idempotent initial deposit is atomic and opening balance does not debit bank twice');
 const snapshot=async()=>{const r=await db.rpc('read_financial_snapshot');assert.equal(r.error,null);return {user:{id:users[0],email:''},...r.data} as Snapshot;};
 const pos=async()=>{const s=await snapshot();return manualSavingsPosition(s,(s.savings_goals as import('../src/lib/summary').Row[]).find(g=>g.id===goal_id)!,today);};
 assert.equal((await pos()).balance,'1000.00');assert.equal((await pos()).profit,null);
 assert.equal((await db.from('account_balances').select('balance').eq('id',account_id).single()).data!.balance,'5000.00');pass('unpriced jar has no invented earnings or bank movement');
 const first=await op('balance',{goal_id,balance:'1100',date:earlier});assert.equal(first.error,null);assert.equal((await pos()).profit,'100.00');
 const deposit=await op('deposit',{goal_id,account_id,amount:'500',date:today});assert.equal(deposit.error,null);
 assert.equal((await op('withdraw',{goal_id,account_id,amount:'300',date:today})).error,null);
 assert.deepEqual(Object.fromEntries(Object.entries(await pos()).filter(([k])=>['deposits','withdrawals','balance','profit','percent'].includes(k))),{deposits:'1500.00',withdrawals:'300.00',balance:'1300.00',profit:'100.00',percent:'6.67'});pass('new deposits and actual withdrawals do not become profits or losses');
 const last=await op('balance',{goal_id,balance:'1350',date:today});assert.equal(last.error,null);
 assert.equal((await pos()).profit,'150.00');assert.equal((await pos()).percent,'10.00');
 assert.equal((await op('balance',{id:first.data.id,goal_id,balance:'1050',date:earlier})).error,null);
 assert.equal((await pos()).balance,'1350.00');assert.equal((await pos()).profit,'150.00');
 const observations=await db.from('manual_savings_updates').select('*').eq('goal_id',goal_id).order('date');assert.equal(observations.data!.length,2);assert.equal(observations.data![0].adjustment,50);assert.equal(observations.data![1].adjustment,100);pass('correcting prior month recomputes only adjustments and preserves subsequent monthly balances');
 assert.equal((await op('deposit',{goal_id,account_id,amount:'100',date:today})).error,null);
 assert.equal((await pos()).balance,'1450.00');assert.equal((await pos()).profit,'150.00');
 let s=await snapshot();const goal=(s.savings_goals as import('../src/lib/summary').Row[]).find(g=>g.id===goal_id)!;
 const history=manualSavingsHistory(s,goal,today);assert.equal(history.at(-1)!.balance,'1350.00');assert.equal(history.at(-1)!.profit,'150.00');assert.equal(history.at(-1)!.invested,'1500.00');pass('same-day flows after an observation never rewrite monthly history or reported profit');
 assert.ok((await db.rpc('cancel_savings_operation',{operation_group:(s.savings_movements as import('../src/lib/summary').Row[]).find(m=>m.type==='manual_withdrawal')!.transaction_group})).error);
 const priorDeposit=(s.savings_movements as import('../src/lib/summary').Row[]).find(m=>m.lot_id===deposit.data.id)!;
 assert.ok((await db.rpc('cancel_savings_operation',{operation_group:priorDeposit.transaction_group})).error);
 pass('legacy cancellation cannot invalidate observed months or lose manual withdrawal capital');
 assert.ok((await other.rpc('manual_savings_operation',{action:'balance',payload:{goal_id,balance:'9',date:today},request_id:randomUUID()})).error);
 assert.deepEqual((await other.from('manual_savings_updates').select('*')).data,[]);
 assert.ok((await db.from('manual_savings_updates').insert({goal_id,date:today,balance:'9'})).error);pass('RLS, ownership and restricted DML prevent cross-user writes and reads');
 for(const bad of ['-1','NaN','Infinity','100.001'])assert.ok((await op('balance',{goal_id,balance:bad,date:today})).error);
 assert.ok((await op('balance',{goal_id,balance:'1',date:'2099-01-01'})).error);
 assert.ok((await op('deposit',{goal_id,account_id,amount:'1',date:earlier})).error);
 assert.ok((await op('withdraw',{goal_id,account_id,amount:'99999',date:today})).error);pass('nonfinite money, future dates, backdated flows and overdrafts are rejected');
 assert.equal((await op('balance',{goal_id,balance:'1000',date:today})).error,null);
 assert.equal((await pos()).profit,'-300.00');
 assert.ok((await db.rpc('execute_operation',{action:'savings_withdraw',payload:{goal_id,account_id,amount:'1100',date:today},request_id:randomUUID()})).error);
 pass('legacy import/API withdrawal cannot overdraw a manually valued jar');
 assert.equal((await op('withdraw',{goal_id,account_id,amount:'1000',date:today})).error,null);
 assert.equal((await pos()).balance,'0.00');assert.equal((await pos()).profit,'-300.00');pass('loss and full withdrawal conserve capital and cumulative losses');
 const lots=await db.from('savings_lots').select('remaining').eq('goal_id',goal_id);assert.ok(lots.data!.every(l=>l.remaining===0));
 assert.ok((await op('balance',{id:last.data.id,goal_id,balance:'0',date:today})).error);pass('invalid retrospective balance cannot create a negative jar or corrupt later withdrawals');
 const journal=await db.from('financial_integrity_revisions').select('entity_id').eq('entity','manual_savings_updates');assert.ok(journal.data!.length>=2);pass('monthly corrections preserve an audit trail');
 const paired=await op('create',{name:'Transferred opening',target:'1000',initial_balance:'500',account_id,date:today});assert.equal(paired.error,null);
 assert.equal((await db.from('account_balances').select('balance').eq('id',account_id).single()).data!.balance,'5200.00');pass('optional initial transfer and later withdrawals update bank exactly once');

 const taxed=await op('create',{name:'Taxed reserve',target:'2000',initial_balance:'1000',date:today});assert.equal(taxed.error,null);
 assert.equal((await op('balance',{goal_id:taxed.data.goal_id,balance:'1100',date:today})).error,null);
 const bankBefore=(await db.from('account_balances').select('balance').eq('id',account_id).single()).data!.balance;
 assert.equal((await op('withdraw',{goal_id:taxed.data.goal_id,account_id,amount:'100',ir_amount:'7',iof_amount:'3',date:today})).error,null);
 const taxedSnapshot=await snapshot();const taxedGoal=(taxedSnapshot.savings_goals as import('../src/lib/summary').Row[]).find(g=>g.id===taxed.data.goal_id)!;
 assert.equal(manualSavingsPosition(taxedSnapshot,taxedGoal,today).profit,'90.00');
 assert.equal(Number((await db.from('account_balances').select('balance').eq('id',account_id).single()).data!.balance)-Number(bankBefore),90);pass('confirmed IR/IOF preserve net bank cash and reduce returns exactly once');
 const concurrent=await op('create',{name:'Concurrent reserve',target:'2000',initial_balance:'1000',date:today});assert.equal(concurrent.error,null);
 assert.equal((await op('balance',{goal_id:concurrent.data.goal_id,balance:'500',date:today})).error,null);
 const withdrawals=await Promise.all([1,2].map(()=>db.rpc('execute_operation',{action:'savings_withdraw',payload:{goal_id:concurrent.data.goal_id,account_id,amount:'400',date:today},request_id:randomUUID()})));
 assert.equal(withdrawals.filter(r=>!r.error).length,1);pass('concurrent legacy withdrawals serialize before balance checks and cannot overdraw losses');
 console.log(`Manual savings checks: ${checks} passed`);
} finally {for(const id of users)assert.equal((await admin.auth.admin.deleteUser(id)).error,null);}
