create extension if not exists pgcrypto;
create table profiles (id uuid primary key references auth.users on delete cascade, name text not null default '', created_at timestamptz not null default now());
create table financial_accounts (
 id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid() references auth.users on delete cascade,
 name text not null, institution text not null default '', kind text not null default 'bank' check(kind in ('bank','cash','savings')), initial_balance numeric(20,2) not null default 0, color text default '#5B35D5', archived boolean not null default false,
 unique(id,user_id));
create table categories (id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid() references auth.users on delete cascade, name text not null, parent_id uuid, budget numeric(20,2) check(budget>=0), unique(id,user_id), foreign key(parent_id,user_id) references categories(id,user_id));
create table credit_cards (id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid() references auth.users on delete cascade, name text not null, institution text default '', brand text default '', last_four text check(last_four ~ '^\d{4}$' or last_four=''), credit_limit numeric(20,2) not null check(credit_limit>0), closing_day int not null check(closing_day between 1 and 28), due_day int not null check(due_day between 1 and 28), account_id uuid not null, unique(id,user_id), foreign key(account_id,user_id) references financial_accounts(id,user_id));
create table transactions (
 id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid() references auth.users on delete cascade, account_id uuid, category_id uuid,
 description text not null, type text not null check(type in ('income','expense','transfer','invoice_payment','investment','redemption','yield','adjustment')), amount numeric(20,2) not null check(amount<>0), date date not null, status text not null default 'confirmed' check(status in ('confirmed','pending')), notes text default '', recurrence text default '', source_id text, group_id uuid,
 unique(user_id,source_id), foreign key(account_id,user_id) references financial_accounts(id,user_id), foreign key(category_id,user_id) references categories(id,user_id));
create index transactions_owner_date on transactions(user_id,date);
create table credit_card_purchases (id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid() references auth.users on delete cascade, card_id uuid not null, description text not null, amount numeric(20,2) not null check(amount>0), date date not null, installments int not null check(installments between 1 and 120), category_id uuid, unique(id,user_id), foreign key(card_id,user_id) references credit_cards(id,user_id), foreign key(category_id,user_id) references categories(id,user_id));
create table credit_card_invoices (id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid() references auth.users on delete cascade, card_id uuid not null, due_date date not null, unique(card_id,due_date), unique(id,user_id), foreign key(card_id,user_id) references credit_cards(id,user_id));
create table credit_card_installments (id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid() references auth.users on delete cascade, purchase_id uuid not null, invoice_id uuid not null, number int not null, amount numeric(20,2) not null check(amount>0), unique(purchase_id,number), foreign key(purchase_id,user_id) references credit_card_purchases(id,user_id), foreign key(invoice_id,user_id) references credit_card_invoices(id,user_id));
create table credit_card_payments (id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid() references auth.users on delete cascade, invoice_id uuid not null, transaction_id uuid not null unique references transactions, amount numeric(20,2) not null check(amount>0), date date not null, foreign key(invoice_id,user_id) references credit_card_invoices(id,user_id));
create table savings_goals (id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid() references auth.users on delete cascade, name text not null, description text default '', account_id uuid not null unique, target numeric(20,2) not null check(target>0), target_date date, institution text default '', indexer text not null default 'cdi' check(indexer in ('none','cdi','fixed','selic','manual')), percentage numeric(10,4) not null default 100 check(percentage>=0), annual_rate numeric(10,4) default 0, product text not null default 'custom', tax_exempt boolean not null default false, unique(id,user_id), foreign key(account_id,user_id) references financial_accounts(id,user_id));
create table savings_lots (id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid() references auth.users on delete cascade, goal_id uuid not null, principal numeric(20,2) not null check(principal>0), remaining numeric(20,2) not null check(remaining>=0), start_date date not null, indexer text not null, percentage numeric(10,4) not null, annual_rate numeric(10,4) default 0, product text not null, tax_exempt boolean not null, unique(id,user_id), foreign key(goal_id,user_id) references savings_goals(id,user_id));
create table savings_movements (id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid() references auth.users on delete cascade, goal_id uuid not null, lot_id uuid, type text not null check(type in ('deposit','withdrawal','confirmed_yield')), amount numeric(20,2) not null check(amount>0), date date not null, transaction_group uuid, foreign key(goal_id,user_id) references savings_goals(id,user_id), foreign key(lot_id,user_id) references savings_lots(id,user_id));
create table investment_assets (id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid() references auth.users on delete cascade, ticker text not null, name text not null, asset_class text not null, currency text not null default 'BRL', cnpj text default '', share_class text default '', maturity date, indexer text default '', percentage numeric(10,4), annual_rate numeric(10,4), unique(user_id,ticker), unique(id,user_id));
create table investment_operations (id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid() references auth.users on delete cascade, asset_id uuid not null, account_id uuid not null, type text not null check(type in ('buy','sell')), quantity numeric(24,8) not null check(quantity>0), price numeric(24,8) not null check(price>0), fees numeric(20,2) not null default 0 check(fees>=0), date date not null, broker text default '', unique(id,user_id), foreign key(asset_id,user_id) references investment_assets(id,user_id), foreign key(account_id,user_id) references financial_accounts(id,user_id));
create table investment_income (id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid() references auth.users on delete cascade, asset_id uuid not null, description text not null, amount numeric(20,2) not null check(amount>0), date date not null, status text not null default 'announced' check(status in ('announced','received')), account_id uuid, type text default 'dividend' check(type in ('dividend','jcp','interest','amortization')), source_id text, unique(user_id,source_id), foreign key(asset_id,user_id) references investment_assets(id,user_id), foreign key(account_id,user_id) references financial_accounts(id,user_id));
create table investment_corporate_actions (id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid() references auth.users on delete cascade, asset_id uuid not null, type text not null check(type in ('split','reverse_split','bonus','ticker_change')), ratio numeric(24,8) not null check(ratio>0), date date not null, new_ticker text, foreign key(asset_id,user_id) references investment_assets(id,user_id));
create table budgets (id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid() references auth.users on delete cascade, name text not null, category_id uuid, amount numeric(20,2) not null check(amount>0), month date not null, foreign key(category_id,user_id) references categories(id,user_id));
create table financial_goals (id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid() references auth.users on delete cascade, name text not null, kind text default 'savings', target numeric(20,2) not null check(target>0), target_date date);
create table user_settings (user_id uuid primary key default auth.uid() references auth.users on delete cascade, name text default '', currency text default 'BRL');
create table benchmark_rates (id uuid primary key default gen_random_uuid(), series text not null, date date not null, value numeric(24,12) not null check(value>=0), source text not null, collected_at timestamptz not null default now(), validated boolean not null default true, revision int not null default 1, unique(series,date));
create table asset_price_history (id uuid primary key default gen_random_uuid(), ticker text not null, date date not null, price numeric(24,8) not null check(price>0), currency text not null default 'BRL', source text not null, collected_at timestamptz not null default now(), unique(ticker,date,source));
create table fund_registry (id text primary key, name text not null, cnpj text not null, administrator text, share_class text, metadata jsonb default '{}');
create table fund_nav_history (id uuid primary key default gen_random_uuid(), fund_id text not null, date date not null, nav numeric(24,8) not null check(nav>0), source text not null, collected_at timestamptz not null default now(), unique(fund_id,date));
create table provider_sync_logs (id uuid primary key default gen_random_uuid(), provider text not null, started_at timestamptz not null default now(), status text not null, records int default 0, message text default '');
create table provider_sync_states (provider text primary key, last_success timestamptz, last_date date);
create table financial_data_providers (name text primary key, mode text default 'automatic', enabled boolean default true);
insert into financial_data_providers(name) values ('bcb'),('brapi'),('cvm');
create table benchmark_rate_revisions (id uuid primary key default gen_random_uuid(), series text, date date, previous_value numeric(24,12), next_value numeric(24,12), changed_at timestamptz default now());
create or replace function audit_rate() returns trigger language plpgsql as $$begin if new.value<>old.value then insert into benchmark_rate_revisions(series,date,previous_value,next_value) values(old.series,old.date,old.value,new.value); new.revision=old.revision+1; end if; return new; end$$;
create trigger rate_revision before update on benchmark_rates for each row execute function audit_rate();
-- Tenant policies and composite foreign keys prevent cross-user references.
do $$ declare t text; begin
 foreach t in array array['financial_accounts','categories','credit_cards','transactions','credit_card_purchases','credit_card_invoices','credit_card_installments','credit_card_payments','savings_goals','savings_lots','savings_movements','investment_assets','investment_operations','investment_income','investment_corporate_actions','budgets','financial_goals','user_settings'] loop
 execute format('alter table %I enable row level security',t);
 execute format('create policy owner on %I for all to authenticated using (user_id=auth.uid()) with check (user_id=auth.uid())',t);
 execute format('grant select,insert,update,delete on %I to authenticated',t);
 end loop;
 foreach t in array array['benchmark_rates','asset_price_history','fund_registry','fund_nav_history','provider_sync_logs','provider_sync_states','financial_data_providers','benchmark_rate_revisions'] loop
 execute format('alter table %I enable row level security',t);
 execute format('create policy market_read on %I for select to authenticated using (true)',t);
 execute format('grant select on %I to authenticated',t);
 end loop;
end $$;
alter table profiles enable row level security;
create policy profile_owner on profiles for all to authenticated using(id=auth.uid()) with check(id=auth.uid());
grant select,insert,update on profiles to authenticated;
create view account_balances with (security_invoker=true) as select a.*, (a.initial_balance+coalesce(sum(t.amount) filter(where t.status='confirmed'),0))::text balance from financial_accounts a left join transactions t on t.account_id=a.id group by a.id;
grant select on account_balances to authenticated;
